version: 2.1
jobs:
  job_1:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest
workflows:
  version: 2
  test:
    jobs:
      - job_1
