version: 2.1

orbs:
  slack: circleci/slack@4.3.1

jobs:
  job_1:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Test React App
          command: npm run test
      - run:
          name: Force Failure
          command: exit 1
      - store_test_results:
          path: test_results

  job_2:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Build React App
          command: |
            npm run build
      - save_cache:
          key: app-build-cache-{{ .Branch }}
          paths:
            - ./build

workflows:
  test-build:
    jobs:
      - job_1
      - job_2:
          requires:
            - job_1
