version: 2.1

jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Test React App
          command: npm run test
      - store_test_results:
          path: test_results

  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Build React App
          command: |
            npm run build
      - save_cache:
          key: app-build-cache-{{ .Branch }}
          paths:
            - ./build

workflows:
  test-build:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - main
